### ISSUE TITLE
Cannot add new friend/WebID in Friends pane - solidcommunity.net server and Ubuntu OS

### ISSUE THREAD

**Issue by mariadimou** [solid/solid-ui#382]
Related to https://github.com/solid/solid-ui/issues/380

I can't add any friends to my Friends pane. 
I follow instructions from https://github.com/solid/userguide/blob/main/views/friends/userguide.md 
The drop drops nothing.
I am https://dimou.solidcommunity.net/, my OS is Ubuntu 20.04 LTS and I tried with Firefox, Chrome and also with Chromium.
This is what Inspect Element shows me for Firefox:
```
Uncaught TypeError: e.forEach is not a function
    d buttons.js:846
    s dragAndDrop.js:103

```
    Thanks in advance for fixing this.

**Comment by mariadimou** [comment]
![Screenshot from 2021-03-04 07-35-01](https://user-images.githubusercontent.com/26465927/109921625-75623b80-7cbc-11eb-91ae-d8eb21a4032b.png)

This is what I see when I try to drag/drop a friend. Please see on the right that I am logged in as Maria Dimou and that I have put Jan Schill's WebID on the URI field and when dragging the dotted square with the cross appears but the drop doesn't complete. 

Thank you again for your attention. 
Maria

**Comment by timbl** [comment]
I don't think it works to put the target URI into the URI bar of the SAME wtab .. if you just overwrite the local URI bar the browser doesn't make it draggable as it doesn'r represent what you are looking at.   You must put it in another tab's url bar and hit return, so that you are looking at Jan Schill in their profile. Thendrag it from that tab into the tab with the friends list.

**Comment by timbl** [comment]
To drag between tabs, drag to the second tab, wait for the body of the tab to be rendered again, then drop within that tab.

**Comment by mariadimou** [comment]
![Screenshot from 2021-03-04 11-38-21](https://user-images.githubusercontent.com/26465927/109999039-1b8c6080-7d12-11eb-9263-c57a08e6225a.png)

In case I shouldn't have tried to drag/drop from the same browser tab I tried also from another browser window, without success. 

I wonder if this is a Ubuntu or a solidcommunity.net issue because @janschill or @timbl don't have this problem. They are on different NSS implementations though!

Thanks for your attention! Looking fwd to your advice!
Maria

**Comment by jeff-zucker** [comment]
It works for me using Linux Mint 20.04 which should be pretty close to Ubuntu with Chrome 89.  I open my profile in one tab, the person's profile in another, click and hold on the lock icon in the location bar of the other person's tab, drag it to my profile tab, hover, my profile appears, I drop the lock icon on it.  I get a new listing on my profile.  That said, there should also be a URL entry option - otherwise instead of just entering the webId URL, I have to open a new tab, enter the webId, go to the page, and then drag it back to where I could have just typed it in in the first place.

**Comment by theRealImy** [comment]
The initial problem cannot be reproduced on Chrome and Firefox. But I can confirm it persists on Safari: https://github.com/solid/solid-ui/issues/380
Manual has been since updated to be more explicit about what to drag.
The second part of the ticket was reflected in a feature request: https://github.com/solid/solidos/issues/45
